# Continuous Integration (CI) is the practice, in software
# engineering, of merging all developer working copies with a shared mainline
# several times a day < http://docs.platformio.org/page/ci/index.html >
#
# Documentation:
#
# * Travis CI Embedded Builds with PlatformIO
#   < https://docs.travis-ci.com/user/integration/platformio/ >
#
# * PlatformIO integration with Travis CI
#   < http://docs.platformio.org/page/ci/travis.html >
#
# * User Guide for `platformio ci` command
#   < http://docs.platformio.org/page/userguide/cmd_ci.html >
#
#
# Please choice one of the following templates (proposed below) and uncomment
# it (remove "# " before each line) or use own configuration according to the
# Travis CI documentation (see above).
#

language: python
python:
- '2.7'
sudo: false
cache:
  directories:
  - ~/.platformio
env:
- PLATFORMIO_CI_SRC=src/
git:
  depth: 3


install:
- pip install -U platformio
- platformio lib install 567 562
after_install:

script:
- platformio run -e nodemcu

after_success:
  # Check that current branch is master, or quit
  - if [[ -z "${TRAVIS_TAG}" ]]; then echo "Deployments are only done for tagged builds."; exit 0; fi
    echo "Deploying build $TRAVIS_BUILD_NUMBER"

deploy:
  on:
    repo: korgan/bsCi
    all_branches: true
    condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$
  skip_cleanup: true
  provider: releases
  overwrite: true
  file: ".pioenvs/nodemcu_deploy/firmware.bin"
